name: npm-publish

on:
  release:
    types: [created]

permissions:
  packages: write
  contents: read

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
          cache: pnpm

      - name: Debug info
        run: |
          node -v
          npm -v
          pnpm store path

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm dist
        env:
          NODE_OPTIONS: --max-old-space-size=6144

      - name: Generate .npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ./.npmrc

      - name: Publish
        run: pnpm pub
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Sync to npmmirror
        run: curl -X PUT -d "sync_upstream=true" "https://registry-direct.npmmirror.com/untiljs/sync"
